import fs from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";

interface PackageJsonContract {
  description: string;
  bin: {
    cam: string;
  };
  files: string[];
  scripts: Record<string, string>;
}

async function readDoc(relativePath: string): Promise<string> {
  return fs.readFile(path.join(process.cwd(), relativePath), "utf8");
}

describe("docs contract", () => {
  it("keeps the public reviewer command surface and deterministic verification entry points documented", async () => {
    const readme = await readDoc("README.md");
    const readmeTw = await readDoc("README.zh-TW.md");
    const readmeEn = await readDoc("README.en.md");
    const readmeJa = await readDoc("README.ja.md");
    const docsReadme = await readDoc("docs/README.md");
    const docsReadmeEn = await readDoc("docs/README.en.md");
    const nativeMigrationEn = await readDoc("docs/native-migration.en.md");
    const releaseChecklist = await readDoc("docs/release-checklist.md");
    const contributing = await readDoc("CONTRIBUTING.md");
    const ciWorkflow = await readDoc(".github/workflows/ci.yml");
    const releaseWorkflow = await readDoc(".github/workflows/release.yml");
    const packageJson = JSON.parse(await readDoc("package.json")) as PackageJsonContract;

    expect(readme).toContain("cam memory");
    expect(readme).toContain("cam session status");
    expect(readme).toContain("cam session refresh");
    expect(readme).toContain("cam recall search");
    expect(readme).toContain("--state auto");
    expect(readme).toContain("当前主任务");
    expect(readme).toContain("suppressed conflict candidates");
    expect(readme).toContain("cam mcp install --host codex");
    expect(readme).toContain("cam hooks install");
    expect(readme).toContain("cam integrations install --host codex");
    expect(readme).toContain("cam integrations apply --host codex");
    expect(readme).toContain("cam integrations doctor --host codex");
    expect(readme).toContain("memory-recall.sh");
    expect(readme).toContain("post-work-memory-review.sh");
    expect(readme).toContain("limit=8");
    expect(readme).toContain("local bridge");
    expect(readme).toContain("cam mcp apply-guidance --host codex");
    expect(readme).toContain("cam skills install");
    expect(readme).toContain("--surface runtime|official-user|official-project");
    expect(readme).toContain("cam mcp serve");
    expect(readme).toContain("cam mcp print-config --host codex");
    expect(readme).toContain("AGENTS.md");
    expect(readme).toContain("cam mcp doctor");
    expect(readme).toContain("alternate global wiring");
    expect(readme).toContain("非 canonical 自定义字段");
    expect(readme).toContain("再退到 resolved CLI");
    expect(readme).toContain("retrieval sidecar 健康度");
    expect(readme).toContain("safe references");
    expect(readme).toContain("postInstallReadinessCommand");
    expect(readme).toContain("recommendedAction");
    expect(readme).toContain("recommendedActionCommand");
    expect(readme).toContain("recommendedDoctorCommand");
    expect(readme).toContain("postApplyReadinessCommand");
    expect(readme).toContain("entryCount");
    expect(readme).toContain("uniqueAuditCount");
    expect(readme).toContain("auditCountsDeduplicated");
    expect(readme).toContain("warningsByEntryRef");
    expect(readme).toContain("leadEntryRef");
    expect(readme).toContain("detailsAvailable");
    expect(readme).toContain("subagent-rollout");
    expect(readme).toContain("manual-only");
    expect(readme).toContain("cam forget \"old debug note\" --archive");
    expect(readme).toContain("`--json`");
    expect(readme).toContain("searchOrder");
    expect(readme).toContain("finalRetrievalMode");
    expect(readme).toContain("totalMatchedCount");
    expect(readme).toContain("returnedCount");
    expect(readme).toContain("globalLimitApplied");
    expect(readme).toContain("truncatedCount");
    expect(readme).toContain("resultWindow");
    expect(readme).toContain("globalRank");
    expect(readme).toContain("droppedCount");
    expect(readme).toContain("summary");
    expect(readme).toContain("entries[]");
    expect(readme).toContain("content highlights");
    expect(readme).toContain("semantic-overwrite");
    expect(readme).toContain("metadata-only");
    expect(readme).toContain("README.zh-TW.md");
    expect(readme).toContain("README.ja.md");
    expect(readme).toContain("集成演进策略");
    expect(readme).toContain("宿主能力面");
    expect(readmeTw).toContain("README.md");
    expect(readmeTw).toContain("README.en.md");
    expect(readmeTw).toContain("memory-recall.sh");
    expect(readmeTw).toContain("cam integrations install --host codex");
    expect(readmeTw).toContain("cam integrations apply --host codex");
    expect(readmeTw).toContain("cam integrations doctor --host codex");
    expect(readmeTw).toContain("limit=8");
    expect(readmeTw).toContain("cam mcp install --host codex");
    expect(readmeTw).toContain("cam mcp print-config --host codex");
    expect(readmeTw).toContain("cam mcp apply-guidance --host codex");
    expect(readmeTw).toContain("cam mcp doctor");
    expect(readmeTw).toContain("alternate global wiring");
    expect(readmeTw).toContain("非 canonical 自訂欄位");
    expect(readmeTw).toContain("再退到 resolved CLI");
    expect(readmeTw).toContain("retrieval sidecar 健康度");
    expect(readmeTw).toContain("safe references");
    expect(readmeTw).toContain("postInstallReadinessCommand");
    expect(readmeTw).toContain("recommendedAction");
    expect(readmeTw).toContain("recommendedActionCommand");
    expect(readmeTw).toContain("recommendedDoctorCommand");
    expect(readmeTw).toContain("postApplyReadinessCommand");
    expect(readmeTw).toContain("entryCount");
    expect(readmeTw).toContain("uniqueAuditCount");
    expect(readmeTw).toContain("auditCountsDeduplicated");
    expect(readmeTw).toContain("warningsByEntryRef");
    expect(readmeTw).toContain("applyReadiness");
    expect(readmeTw).toContain("stateResolution");
    expect(readmeTw).toContain("executionSummary");
    expect(readmeTw).toContain("returnedCount");
    expect(readmeTw).toContain("searchOrder");
    expect(readmeTw).toContain("totalMatchedCount");
    expect(readmeTw).toContain("globalLimitApplied");
    expect(readmeTw).toContain("truncatedCount");
    expect(readmeTw).toContain("resultWindow");
    expect(readmeTw).toContain("globalRank");
    expect(readmeTw).toContain("finalRetrievalMode");
    expect(readmeTw).toContain("droppedCount");
    expect(readmeTw).toContain("entries[]");
    expect(readmeTw).toContain("experimentalHooks");
    expect(readmeTw).toContain("--state auto");
    expect(readmeTw).toContain("`cam memory` / `cam session` / `cam recall` / `cam audit`");
    expect(readmeTw).toContain("local bridge");
    expect(readmeTw).toContain("| `cam hooks install` |");
    expect(readmeTw).toContain("manual-only");
    expect(readmeTw).toContain("--surface runtime|official-user|official-project");
    expect(readmeTw).toContain("重要 `--help` 文案");
    expect(readmeTw).toContain("release-facing public contract");
    expect(readmeJa).toContain("README.md");
    expect(readmeJa).toContain("README.en.md");
    expect(readmeJa).toContain("memory-recall.sh");
    expect(readmeJa).toContain("cam integrations install --host codex");
    expect(readmeJa).toContain("cam integrations apply --host codex");
    expect(readmeJa).toContain("cam integrations doctor --host codex");
    expect(readmeJa).toContain("limit=8");
    expect(readmeJa).toContain("cam mcp install --host codex");
    expect(readmeJa).toContain("cam mcp print-config --host codex");
    expect(readmeJa).toContain("cam mcp apply-guidance --host codex");
    expect(readmeJa).toContain("cam mcp doctor");
    expect(readmeJa).toContain("alternate global wiring");
    expect(readmeJa).toContain("non-canonical なカスタム項目");
    expect(readmeJa).toContain("resolved CLI recall");
    expect(readmeJa).toContain("retrieval sidecar");
    expect(readmeJa).toContain("safe references");
    expect(readmeJa).toContain("postInstallReadinessCommand");
    expect(readmeJa).toContain("recommendedAction");
    expect(readmeJa).toContain("recommendedActionCommand");
    expect(readmeJa).toContain("recommendedDoctorCommand");
    expect(readmeJa).toContain("postApplyReadinessCommand");
    expect(readmeJa).toContain("entryCount");
    expect(readmeJa).toContain("uniqueAuditCount");
    expect(readmeJa).toContain("auditCountsDeduplicated");
    expect(readmeJa).toContain("warningsByEntryRef");
    expect(readmeJa).toContain("applyReadiness");
    expect(readmeJa).toContain("stateResolution");
    expect(readmeJa).toContain("executionSummary");
    expect(readmeJa).toContain("returnedCount");
    expect(readmeJa).toContain("searchOrder");
    expect(readmeJa).toContain("totalMatchedCount");
    expect(readmeJa).toContain("globalLimitApplied");
    expect(readmeJa).toContain("truncatedCount");
    expect(readmeJa).toContain("resultWindow");
    expect(readmeJa).toContain("globalRank");
    expect(readmeJa).toContain("finalRetrievalMode");
    expect(readmeJa).toContain("droppedCount");
    expect(readmeJa).toContain("retrievalFallbackReason");
    expect(readmeJa).toContain("entries[]");
    expect(readmeJa).toContain("latestLifecycleAction");
    expect(readmeJa).toContain("latestAudit");
    expect(readmeJa).toContain("highlightCount");
    expect(readmeJa).toContain("startupSectionsRendered");
    expect(readmeJa).toContain("experimentalHooks");
    expect(readmeJa).toContain("--state auto");
    expect(readmeJa).toContain("`cam memory` / `cam session` / `cam recall` / `cam audit`");
    expect(readmeJa).toContain("local bridge");
    expect(readmeJa).toContain("| `cam hooks install` |");
    expect(readmeJa).toContain("manual-only");
    expect(readmeJa).toContain("--surface runtime|official-user|official-project");
    expect(readmeJa).toContain("主要な `--help` 文言");
    expect(readmeJa).toContain("release-facing public contract");
    expect(readmeEn).toContain("cam memory");
    expect(readmeEn).toContain("cam session status");
    expect(readmeEn).toContain("cam recall search");
    expect(readmeEn).toContain("--state auto");
    expect(readmeEn).toContain("confidence");
    expect(readmeEn).toContain("suppressed conflict candidates");
    expect(readmeEn).toContain("wrapper-driven companion layer");
    expect(readmeEn).toContain("cam mcp install --host codex");
    expect(readmeEn).toContain("README.zh-TW.md");
    expect(readmeEn).toContain("README.ja.md");
    expect(readmeEn).toContain("hook, skill, and MCP-aware");
    expect(readmeEn).toContain("cam hooks");
    expect(readmeEn).toContain("cam integrations install --host codex");
    expect(readmeEn).toContain("cam integrations apply --host codex");
    expect(readmeEn).toContain("cam integrations doctor --host codex");
    expect(readmeEn).toContain("cam skills");
    expect(readmeEn).toContain("memory-recall.sh");
    expect(readmeEn).toContain("post-work-memory-review.sh");
    expect(readmeEn).toContain("limit=8");
    expect(readmeEn).toContain("local bridge");
    expect(readmeEn).toContain("cam mcp apply-guidance --host codex");
    expect(readmeEn).toContain("cam mcp serve");
    expect(readmeEn).toContain("cam mcp print-config --host codex");
    expect(readmeEn).toContain("AGENTS.md");
    expect(readmeEn).toContain("cam mcp doctor");
    expect(readmeEn).toContain("alternate global wiring");
    expect(readmeEn).toContain("non-canonical custom fields");
    expect(readmeEn).toContain("before the resolved CLI recall commands");
    expect(readmeEn).toContain("retrieval-sidecar health");
    expect(readmeEn).toContain("safe references");
    expect(readmeEn).toContain("postInstallReadinessCommand");
    expect(readmeEn).toContain("recommendedAction");
    expect(readmeEn).toContain("recommendedActionCommand");
    expect(readmeEn).toContain("recommendedDoctorCommand");
    expect(readmeEn).toContain("postApplyReadinessCommand");
    expect(readmeEn).toContain("entryCount");
    expect(readmeEn).toContain("uniqueAuditCount");
    expect(readmeEn).toContain("auditCountsDeduplicated");
    expect(readmeEn).toContain("warningsByEntryRef");
    expect(readmeEn).toContain("leadEntryRef");
    expect(readmeEn).toContain("detailsAvailable");
    expect(readmeEn).toContain("subagent-rollout");
    expect(readmeEn).toContain("manual-only");
    expect(readmeEn).toContain("searchOrder");
    expect(readmeEn).toContain("finalRetrievalMode");
    expect(readmeEn).toContain("totalMatchedCount");
    expect(readmeEn).toContain("returnedCount");
    expect(readmeEn).toContain("globalLimitApplied");
    expect(readmeEn).toContain("truncatedCount");
    expect(readmeEn).toContain("resultWindow");
    expect(readmeEn).toContain("globalRank");
    expect(readmeEn).toContain("droppedCount");
    expect(readmeEn).toContain("retrievalFallbackReason");
    expect(readmeEn).toContain("summary");
    expect(readmeEn).toContain("entries[]");
    expect(readmeEn).toContain("latestLifecycleAction");
    expect(readmeEn).toContain("latestAudit");
    expect(readmeEn).toContain("highlightCount");
    expect(readmeEn).toContain("startupSectionsRendered");
    expect(readmeEn).toContain("content highlights");
    expect(readmeEn).toContain("semantic-overwrite");
    expect(readmeEn).toContain("metadata-only");
    expect(readmeEn).toContain("| `cam hooks install` |");
    expect(readmeEn).toContain("`cam memory`, `cam session`, and `cam recall` reviewer UX");
    expect(readmeEn).toContain("--surface runtime|official-user|official-project");
    expect(docsReadme).toContain("Codex-first Hybrid");
    expect(docsReadme).toContain("cam mcp apply-guidance --host codex");
    expect(docsReadme).toContain("cam integrations apply --host codex");
    expect(docsReadme).toContain("cam integrations doctor --host codex");
    expect(docsReadme).toContain("runtime|official-user|official-project");
    expect(docsReadme).toContain("manual-only");
    expect(docsReadme).toContain("`--help` 文案");
    expect(docsReadme).toContain("state=auto");
    expect(docsReadme).toContain("experimentalHooks");
    expect(docsReadme).toContain("stateResolution");
    expect(docsReadme).toContain("commandName=cam");
    expect(docsReadme).toContain("searchOrder");
    expect(docsReadme).toContain("totalMatchedCount");
    expect(docsReadme).toContain("globalLimitApplied");
    expect(docsReadme).toContain("resultWindow");
    expect(docsReadme).toContain("droppedCount");
    expect(docsReadme).toContain("retrievalFallbackReason");
    expect(docsReadme).toContain("entries[]");
    expect(docsReadme).toContain("latestLifecycleAction");
    expect(docsReadme).toContain("latestAudit");
    expect(docsReadme).toContain("highlightCount");
    expect(docsReadme).toContain("startupSectionsRendered");
    expect(docsReadme).toContain("content highlights");
    expect(docsReadmeEn).toContain("Codex-first Hybrid");
    expect(docsReadmeEn).toContain("cam mcp apply-guidance --host codex");
    expect(docsReadmeEn).toContain("cam integrations apply --host codex");
    expect(docsReadmeEn).toContain("cam integrations doctor --host codex");
    expect(docsReadmeEn).toContain("runtime`, `official-user`, and `official-project");
    expect(docsReadmeEn).toContain("manual-only");
    expect(docsReadmeEn).toContain("`--help` text is part of the release-facing public contract");
    expect(docsReadmeEn).toContain("state=auto, limit=8");
    expect(docsReadmeEn).toContain("experimentalHooks");
    expect(docsReadmeEn).toContain("stateResolution");
    expect(docsReadmeEn).toContain("commandName=cam");
    expect(docsReadmeEn).toContain("searchOrder");
    expect(docsReadmeEn).toContain("totalMatchedCount");
    expect(docsReadmeEn).toContain("globalLimitApplied");
    expect(docsReadmeEn).toContain("resultWindow");
    expect(docsReadmeEn).toContain("droppedCount");
    expect(docsReadmeEn).toContain("retrievalFallbackReason");
    expect(docsReadmeEn).toContain("entries[]");
    expect(docsReadmeEn).toContain("latestLifecycleAction");
    expect(docsReadmeEn).toContain("latestAudit");
    expect(docsReadmeEn).toContain("highlightCount");
    expect(docsReadmeEn).toContain("startupSectionsRendered");
    expect(docsReadmeEn).toContain("content highlights");
    expect(nativeMigrationEn).toContain("native Codex memory and hooks are still not ready");
    expect(nativeMigrationEn).toContain("allow non-native integration expansion");
    expect(releaseChecklist).toContain("pnpm test:dist-cli-smoke");
    expect(releaseChecklist).toContain("pnpm test:tarball-install-smoke");
    expect(releaseChecklist).toContain("node dist/cli.js --version");
    expect(releaseChecklist).toContain("node dist/cli.js audit");
    expect(releaseChecklist).toContain("pnpm test:docs-contract");
    expect(releaseChecklist).toContain("pnpm test:reviewer-smoke");
    expect(releaseChecklist).toContain("pnpm test:cli-smoke");
    expect(releaseChecklist).toContain("pnpm pack:check");
    expect(releaseChecklist).toContain("package.json.files");
    expect(releaseChecklist).toContain("node dist/cli.js session refresh --json");
    expect(releaseChecklist).toContain("node dist/cli.js session load --json");
    expect(releaseChecklist).toContain("node dist/cli.js session status --json");
    expect(releaseChecklist).toContain("node dist/cli.js recall search pnpm --json");
    expect(releaseChecklist).toContain("state=auto, limit=8");
    expect(releaseChecklist).toContain("checkedPaths");
    expect(releaseChecklist).toContain('stateResolution.outcome: "explicit-state"');
    expect(releaseChecklist).toContain("searchOrder");
    expect(releaseChecklist).toContain("totalMatchedCount");
    expect(releaseChecklist).toContain("returnedCount");
    expect(releaseChecklist).toContain("globalLimitApplied");
    expect(releaseChecklist).toContain("truncatedCount");
    expect(releaseChecklist).toContain("resultWindow");
    expect(releaseChecklist).toContain("globalRank");
    expect(releaseChecklist).toContain("droppedCount");
    expect(releaseChecklist).toContain("node dist/cli.js remember \"...\" --json");
    expect(releaseChecklist).toContain("node dist/cli.js forget \"...\" --json");
    expect(releaseChecklist).toContain("entries[]");
    expect(releaseChecklist).toContain("summary");
    expect(releaseChecklist).toContain("noop attempt");
    expect(releaseChecklist).toContain("highlightCount");
    expect(releaseChecklist).toContain("omittedHighlightCount");
    expect(releaseChecklist).toContain("omittedTopicFileCount");
    expect(releaseChecklist).toContain("topicFileOmissionCounts");
    expect(releaseChecklist).toContain("topicRefCountsByScope");
    expect(releaseChecklist).toContain("highlightsByScope");
    expect(releaseChecklist).toContain("startupSectionsRendered");
    expect(releaseChecklist).toContain("node dist/cli.js memory reindex --scope all --state all --json");
    expect(releaseChecklist).toContain("### Highlights");
    expect(releaseChecklist).toContain("node dist/cli.js recall details <ref> --json");
    expect(releaseChecklist).toContain("latestLifecycleAction");
    expect(releaseChecklist).toContain("latestSessionId");
    expect(releaseChecklist).toContain("latestRolloutPath");
    expect(releaseChecklist).toContain("historyPath");
    expect(releaseChecklist).toContain("latestAudit");
    expect(releaseChecklist).toContain("latestState");
    expect(releaseChecklist).toContain("timelineWarningCount");
    expect(releaseChecklist).toContain("lineageSummary");
    expect(releaseChecklist).toContain("warnings");
    expect(releaseChecklist).toContain(
      "node dist/cli.js mcp install --host codex --json"
    );
    expect(releaseChecklist).toContain('action: "unchanged"');
    expect(releaseChecklist).toContain("node dist/cli.js mcp install --host generic");
    expect(releaseChecklist).toContain(
      "node dist/cli.js mcp print-config --host <codex|claude|gemini|generic> --json"
    );
    expect(releaseChecklist).toContain("AGENTS.md snippet");
    expect(releaseChecklist).toContain("node dist/cli.js mcp apply-guidance --host codex --json");
    expect(releaseChecklist).toContain('returns `blocked`');
    expect(releaseChecklist).toContain("node dist/cli.js mcp doctor --json");
    expect(releaseChecklist).toContain("node dist/cli.js mcp doctor --host codex --json");
    expect(releaseChecklist).toContain("structured `workflowContract`");
    expect(releaseChecklist).toContain("retrievalSidecar");
    expect(releaseChecklist).toContain("MCP -> local bridge -> resolved CLI");
    expect(releaseChecklist).toContain("repair command");
    expect(releaseChecklist).toContain("hookCaptureOperationalReady");
    expect(releaseChecklist).toContain("commandName=cam");
    expect(releaseChecklist).toContain("node <installed>/dist/cli.js");
    expect(releaseChecklist).toContain("alternate global wiring");
    expect(releaseChecklist).toContain("non-canonical custom fields");
    expect(releaseChecklist).toContain("preservedCustomFields");
    expect(releaseChecklist).toContain("configScopeSummary");
    expect(releaseChecklist).toContain("alternateWiring");
    expect(releaseChecklist).toContain("runtimeSkillPresent");
    expect(releaseChecklist).toContain("officialUserSkillMatchesCanonical");
    expect(releaseChecklist).toContain("anySkillSurfaceInstalled");
    expect(releaseChecklist).toContain("post-work-memory-review.sh");
    expect(releaseChecklist).toContain("node dist/cli.js hooks install --json");
    expect(releaseChecklist).toContain("postInstallReadinessCommand");
    expect(releaseChecklist).toContain("node dist/cli.js skills install --json");
    expect(releaseChecklist).toContain("node dist/cli.js integrations install --host codex --json");
    expect(releaseChecklist).toContain("node dist/cli.js integrations apply --host codex --json");
    expect(releaseChecklist).toContain('stackAction: "blocked"');
    expect(releaseChecklist).toContain("preflightBlocked");
    expect(releaseChecklist).toContain("skipped subactions");
    expect(releaseChecklist).toContain("applyReadiness");
    expect(releaseChecklist).toContain("recommendedRoute");
    expect(releaseChecklist).toContain("recommendedAction");
    expect(releaseChecklist).toContain("recommendedActionCommand");
    expect(releaseChecklist).toContain("recommendedDoctorCommand");
    expect(releaseChecklist).toContain("finalRetrievalMode");
    expect(releaseChecklist).toContain("entryCount");
    expect(releaseChecklist).toContain("warningCount");
    expect(releaseChecklist).toContain("detailsUsableEntryCount");
    expect(releaseChecklist).toContain("timelineOnlyEntryCount");
    expect(releaseChecklist).toContain("node dist/cli.js skills install --surface official-user");
    expect(releaseChecklist).toContain("node dist/cli.js integrations install --host codex --skill-surface official-user --json");
    expect(releaseChecklist).toContain("node dist/cli.js integrations apply --host codex --skill-surface official-user --json");
    expect(releaseChecklist).toContain("node dist/cli.js skills install --surface official-project");
    expect(releaseChecklist).toContain("node dist/cli.js integrations install --host codex --skill-surface official-project --json");
    expect(releaseChecklist).toContain("node dist/cli.js integrations apply --host codex --skill-surface official-project --json");
    expect(releaseChecklist).toContain("node dist/cli.js integrations doctor --host codex --json");
    expect(releaseChecklist).toContain("node dist/cli.js mcp install --help");
    expect(releaseChecklist).toContain("node dist/cli.js mcp print-config --help");
    expect(releaseChecklist).toContain("node dist/cli.js mcp apply-guidance --help");
    expect(releaseChecklist).toContain("node dist/cli.js mcp doctor --help");
    expect(releaseChecklist).toContain("node dist/cli.js skills install --help");
    expect(releaseChecklist).toContain("node dist/cli.js integrations install --help");
    expect(releaseChecklist).toContain("node dist/cli.js integrations apply --help");
    expect(releaseChecklist).toContain("node dist/cli.js integrations doctor --help");
    expect(releaseChecklist).toContain("node dist/cli.js skills install --surface official-project --cwd <path>");
    expect(releaseChecklist).toContain("node dist/cli.js mcp apply-guidance --host codex --cwd <path> --json");
    expect(releaseChecklist).toContain("node dist/cli.js integrations apply --host codex --cwd <path> --json");
    expect(releaseChecklist).toContain("codex only");
    expect(releaseChecklist).toContain("manual-only and snippet-first");
    expect(releaseChecklist).toContain("README.zh-TW.md");
    expect(releaseChecklist).toContain("README.ja.md");
    expect(releaseChecklist).toContain("search_memories");
    expect(contributing).toContain("reviewer-only warnings");
    expect(contributing).toContain("pnpm test:docs-contract");
    expect(contributing).toContain("pnpm test:dist-cli-smoke");
    expect(contributing).toContain("pnpm test:tarball-install-smoke");
    expect(contributing).toContain("cam mcp apply-guidance");
    expect(contributing).toContain("cam integrations apply");
    expect(contributing).toContain("skill surface selection");
    expect(packageJson.scripts["test:cli-smoke"]).toContain("test/recall-command.test.ts");
    expect(packageJson.scripts["test:cli-smoke"]).toContain("test/doctor-command.test.ts");
    expect(packageJson.scripts["test:cli-smoke"]).toContain("test/hooks-command.test.ts");
    expect(packageJson.scripts["test:cli-smoke"]).toContain("test/integrations-command.test.ts");
    expect(packageJson.scripts["test:cli-smoke"]).toContain("test/mcp-command.test.ts");
    expect(packageJson.scripts["test:cli-smoke"]).toContain("test/skills-command.test.ts");
    expect(packageJson.scripts["test:reviewer-smoke"]).toContain("test/recall-command.test.ts");
    expect(packageJson.scripts["test:reviewer-smoke"]).toContain("test/doctor-command.test.ts");
    expect(packageJson.scripts["test:reviewer-smoke"]).toContain("test/hooks-command.test.ts");
    expect(packageJson.scripts["test:reviewer-smoke"]).toContain("test/integrations-command.test.ts");
    expect(packageJson.scripts["test:reviewer-smoke"]).toContain("test/mcp-command.test.ts");
    expect(packageJson.scripts["test:reviewer-smoke"]).toContain("test/skills-command.test.ts");
    expect(packageJson.scripts["test:dist-cli-smoke"]).toBe("vitest run test/dist-cli-smoke.test.ts");
    expect(packageJson.scripts["test:tarball-install-smoke"]).toBe(
      "vitest run test/tarball-install-smoke.test.ts"
    );
    expect(packageJson.description).toBe(
      "A Markdown-first, local-first memory runtime for Codex with wrapper, hook, MCP, skill, and AGENTS integration surfaces."
    );
    expect(packageJson.bin.cam).toBe("dist/cli.js");
    expect(packageJson.files).toEqual(
      expect.arrayContaining([
        "dist",
        "docs",
        "schemas",
        "README.md",
        "README.zh-TW.md",
        "README.en.md",
        "README.ja.md",
        "LICENSE"
      ])
    );
    expect(packageJson.scripts.prepack).toBe("pnpm build");
    expect(packageJson.scripts["verify:release"]).toContain("pnpm test:dist-cli-smoke");
    expect(packageJson.scripts["verify:release"]).toContain("pnpm test:tarball-install-smoke");
    expect(ciWorkflow).toContain("Dist CLI Smoke");
    expect(ciWorkflow).toContain("Tarball Install Smoke");
    expect(releaseWorkflow).toContain("tags:");
    expect(releaseWorkflow).toContain("v*");
    expect(releaseWorkflow).toContain("pnpm verify:release");
    expect(releaseWorkflow).toContain("gh release create");
    expect(releaseChecklist).toContain("default branch");
    expect(releaseChecklist).toContain("remote default branch exposes `release.yml` in Actions");
    expect(releaseChecklist).toContain("workflow is active");
  });

  it("keeps continuity, architecture, and migration wording aligned with the current product posture", async () => {
    const continuityDoc = await readDoc("docs/session-continuity.md");
    const nativeMigrationDoc = await readDoc("docs/native-migration.md");
    const architecture = await readDoc("docs/architecture.md");
    const architectureEn = await readDoc("docs/architecture.en.md");
    const integrationStrategy = await readDoc("docs/integration-strategy.md");
    const hostSurfaces = await readDoc("docs/host-surfaces.md");
    const readme = await readDoc("README.md");
    const readmeEn = await readDoc("README.en.md");
    const registerCommands = await readDoc("src/lib/cli/register-commands.ts");

    expect(continuityDoc).toContain("save` keeps merge semantics");
    expect(continuityDoc).toContain("refresh` ignores existing continuity");
    expect(continuityDoc).toContain("pending continuity recovery marker");
    expect(continuityDoc).toContain("**not** written into the continuity Markdown files themselves");
    expect(continuityDoc).toContain("reviewer/debug data belongs in an audit surface");
    expect(continuityDoc).toContain("future integration surfaces should consume continuity");
    expect(nativeMigrationDoc).toContain("companion-first");
    expect(nativeMigrationDoc).toContain("trusted primary path");
    expect(nativeMigrationDoc).toContain("Codex-first Hybrid");
    expect(architecture).toContain("reviewer warning / confidence 属于 audit side metadata");
    expect(architecture).toContain("startup provenance 只列出真实读取到的 continuity 文件");
    expect(architecture).toContain("cam recall");
    expect(architecture).toContain("memory-recall.sh");
    expect(architecture).toContain("cam mcp serve");
    expect(architecture).toContain("cam mcp install");
    expect(architecture).toContain("--surface runtime|official-user|official-project");
    expect(architecture).toContain("manual-only");
    expect(architecture).toContain("cam mcp apply-guidance");
    expect(architecture).toContain("cam integrations install --host codex");
    expect(architecture).toContain("cam integrations apply --host codex");
    expect(architecture).toContain("cam integrations doctor --host codex");
    expect(architecture).toContain("state=auto");
    expect(architecture).toContain("local bridge / fallback recall bundle");
    expect(architecture).toContain("cam mcp print-config");
    expect(architecture).toContain("cam mcp doctor");
    expect(architecture).toContain("release-facing `--help` surfaces");
    expect(architecture).toContain("Codex-first Hybrid");
    expect(architectureEn).toContain("reviewer warnings and confidence remain audit-side metadata");
    expect(architectureEn).toContain("cam recall timeline");
    expect(architectureEn).toContain("cam mcp serve");
    expect(architectureEn).toContain("cam mcp install");
    expect(architectureEn).toContain("state=auto, limit=8");
    expect(architectureEn).toContain("local bridge assets");
    expect(architectureEn).toContain("cam mcp print-config");
    expect(architectureEn).toContain("cam mcp doctor");
    expect(architectureEn).toContain("memory-recall.sh");
    expect(architectureEn).toContain("continuity startup provenance only lists files actually used");
    expect(architectureEn).toContain("Codex-first Hybrid");
    expect(integrationStrategy).toContain("Codex-first Hybrid");
    expect(integrationStrategy).toContain("hook / skill / MCP");
    expect(integrationStrategy).toContain("cam recall");
    expect(integrationStrategy).toContain("state=auto");
    expect(integrationStrategy).toContain("limit=8");
    expect(integrationStrategy).toContain("cam mcp install");
    expect(integrationStrategy).toContain("cam mcp apply-guidance");
    expect(integrationStrategy).toContain("memory-recall.sh");
    expect(integrationStrategy).toContain("post-work-memory-review.sh");
    expect(integrationStrategy).toContain("local bridge / fallback helper bundle");
    expect(integrationStrategy).toContain("cam mcp serve");
    expect(integrationStrategy).toContain("cam mcp print-config");
    expect(integrationStrategy).toContain("AGENTS.md");
    expect(integrationStrategy).toContain("cam mcp doctor");
    expect(integrationStrategy).toContain("manual-only");
    expect(integrationStrategy).toContain("continuity files 属于临时 working state / reviewer surface");
    expect(integrationStrategy).toContain("不是 canonical durable memory");
    expect(integrationStrategy).toContain("audit / provenance logs 属于 reviewer / audit side evidence");
    expect(integrationStrategy).toContain("cam integrations install --host codex");
    expect(integrationStrategy).toContain("cam integrations doctor --host codex");
    expect(integrationStrategy).toContain("release-facing `--help` 文案");
    expect(integrationStrategy).toContain("cam skills install");
    expect(integrationStrategy).toContain("--surface runtime|official-user|official-project");
    expect(hostSurfaces).toContain("Codex-first Hybrid memory system");
    expect(hostSurfaces).toContain("cam integrations install/apply --skill-surface");
    expect(hostSurfaces).toContain("cam recall");
    expect(hostSurfaces).toContain("cam hooks install");
    expect(hostSurfaces).toContain("local bridge");
    expect(hostSurfaces).toContain("read-only retrieval surface");
    expect(hostSurfaces).toContain("cam mcp install");
    expect(hostSurfaces).toContain("manual-only");
    expect(hostSurfaces).toContain("cam mcp apply-guidance");
    expect(hostSurfaces).toContain("AGENTS.md");
    expect(hostSurfaces).toContain("cam mcp doctor");
    expect(hostSurfaces).toContain("cam integrations install");
    expect(hostSurfaces).toContain("cam integrations doctor");
    expect(hostSurfaces).toContain("release-facing `--help` 文案");
    expect(readme).toContain("companion-first");
    expect(readmeEn).toContain("companion CLI");
    expect(readme).toContain("当前主任务");
    expect(readmeEn).toContain("Current priorities");
    expect(readme).toContain("workflowContract");
    expect(readme).toContain("preflight `blocked`");
    expect(readme).toContain("applyReadiness");
    expect(readmeEn).toContain("workflowContract");
    expect(readmeEn).toContain("preflight `blocked`");
    expect(readmeEn).toContain("applyReadiness");
    expect(registerCommands).toContain(
      "Manage the local bridge / fallback helper bundle for current and upcoming integrations"
    );
    expect(registerCommands).toContain(
      "Generate the local bridge / fallback helper bundle, including recall, startup, post-session, and post-work review helpers"
    );
  });
});
